### ISSUE TITLE
Displays starttls imap connection as Unencrypted

### ISSUE THREAD

**Issue by jspricke** [SecUSo/privacy-friendly-netmonitor#11]
I tried the current version in F-Droid (1.0) with K9-Mail 5.203 using a imap connection with starttls (checked on the other side). Netmonitor displays it as imap and unencrypted.

**Comment by Tungdal** [comment]
Yes, I've got the same Problem. I'm using posteo.de with Starttls, Netmonitor recognized it as "Unencrypted (imap, tcp6)".

**Comment by schillef** [comment]
This "error" arises from the fact that STARTTLS uses the same port numbers as the unencrypted e-mail protocol types. It "upgrades" an unencrypted communication with TLS behaviour. Direct TLS connections normally use different port numbers.

    IMAP uses port 143, but SSL/TLS encrypted IMAP uses port 993.
    POP uses port 110, but SSL/TLS encrypted POP uses port 995.
    SMTP uses port 25, but SSL/TLS encrypted SMTP uses port 465.

As the app has only access to portnumbers of connected sockets and therefore makes an assumption on the employed protocols (as stated in the help-topics). The behaviour of STARTTLS bypasses the Well-Known port association and therefore a correct identification of the protocol.

Since STARTTLS is a widespread protocol, additional information for those dual-used e-mail ports could be displayed in the next relase.

Thanks for reporting this behaviour :).

Cheers,

Felix

**Comment by schillef** [comment]
This issue has been addressed with a new category "inconclusive" for multi-used ports
