### ISSUE TITLE
Question about hidden connections

### ISSUE THREAD

**Issue by highfellow** [SecUSo/privacy-friendly-netmonitor#76]
I would like to ask what thought you gave in writing this app to the possibility that some processes might be making network connections in a way which is deliberately hidden from the operating system and hence from this monitor? Is this something that is possible in Android. My reason for installing this app was to try to answer a nagging feeling that my Android phone was being used to spy on me. Having identified all the open connections I feel a bit safer in this respect, but I am wondering whether a real piece of spyware would be able to hide its activities from an app like this?

Thanks for your efforts in writing these privacy friendly apps by the way. Digital rights is an important issue and I am glad there are people like you willing to do this work.

**Comment by schillef** [comment]
Hey Andrew,

glad you like the Project! 🙂

This App was Designer to be the consumer friendly Version of my Thesis App, where network flow should be investigated in terms of Solid encryption.

Since the Security of the Android Framework is working quite well, the original App was only working on rooted Devices.

The App takes the existant connections from the underlying Linux Kernel and matches thembto the invoicing Apps. So that's the connections (sockets) that are opened by the System on the transport layer. There would still be posibilities where traffic is hidden within those connections, but with the Android sandboxing models, the communicating apps are comprehensively listed.

Please Note that the App is now developed by the institute SECUSO at TU Darmstadt and that Students are develpoing this app further. I am very happy about that, because I'm not there anymore to develop that app by myself.

Please ask if you have further questions.

- Felix 

Am 13. November 2019 06:17:22 MEZ schrieb Andrew Baxter <notifications@github.com>:
>I would like to ask what thought you gave in writing this app to the
>possibility that some processes might be making network connections in
>a way which is deliberately hidden from the operating system and hence
>from this monitor? Is this something that is possible in Android. My
>reason for installing this app was to try to answer a nagging feeling
>that my Android phone was being used to spy on me. Having identified
>all the open connections I feel a bit safer in this respect, but I am
>wondering whether a real piece of spyware would be able to hide its
>activities from an app like this?
>
>Thanks for your efforts in writing these privacy friendly apps by the
>way. Digital rights is an important issue and I am glad there are
>people like you willing to do this work.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SecUSo/privacy-friendly-netmonitor/issues/76

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Kamuno** [comment]
Thanks for answering, Felix. 

One little correction: The SECUSO Research Group now moved to the Karlsruhe Instuture of Technology. However, it is still true that the Privacy Friendly Apps are being developed by Computer Science students. 

I will close this issue for now. If any more questions come up, don't hesitate to open a new issue.
